// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmdvanoqqzrqzwdhfphi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtZHZhbm9xcXpycXp3ZGhmcGhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4NzE1OTIsImV4cCI6MjA4NjQ0NzU5Mn0.LkEGJdm6MUoQnrrBW94R0FhVkrILheV8SdqpVID3WwA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});